name = "route-visualization"
main = "worker.js"
compatibility_date = "2023-12-01"

# Directory with static assets
site = { bucket = "./public" }

# Environment variables will be set in the Cloudflare dashboard
[vars]
MAPBOX_TOKEN = ""
GEMINI_API_KEY = ""

# Enable functions for API endpoints
[site.functions]
directory = "functions"

# Remove the routes section as it's not needed for the Workers dev domain
# [[routes]]
# pattern = "api.yourdomain.com/*"
# zone_name = "yourdomain.com"

# Properly define the site asset configuration
[site]
bucket = "./public" 